In [100]:
import pandas as pd
import numpy as np


Y =  [78.5, 74.3, 104.3, 87.6, 95.9, 109.2, 102.7, 72.5, 93.1, 115.9, 83.8, 113.3, 109.4]
X1 = [7, 1, 11, 11, 7, 11, 3, 1, 2, 21, 1, 11, 10]
X2 = [26, 29, 56, 31, 52, 55, 71, 31, 54, 47, 40, 66, 68]
X3 = [6, 15, 8, 8, 6, 9, 17, 22, 18, 4, 23, 9, 8]
X4 = [60, 52, 20, 47, 33, 22, 6, 44, 22, 26, 34, 12, 12]

df = pd.DataFrame({
    "Y": Y,
    "X1": X1,
    "X2": X2,
    "X3": X3,
    "X4": X4
})
df


Y  X1  X2  X3  X4
0    78.5   7  26   6  60
1    74.3   1  29  15  52
2   104.3  11  56   8  20
3    87.6  11  31   8  47
4    95.9   7  52   6  33
5   109.2  11  55   9  22
6   102.7   3  71  17   6
7    72.5   1  31  22  44
8    93.1   2  54  18  22
9   115.9  21  47   4  26
10   83.8   1  40  23  34
11  113.3  11  66   9  12
12  109.4  10  68   8  12

In [101]:
df2 = df.copy()
df2['Y']=1
df2

Y  X1  X2  X3  X4
0   1   7  26   6  60
1   1   1  29  15  52
2   1  11  56   8  20
3   1  11  31   8  47
4   1   7  52   6  33
5   1  11  55   9  22
6   1   3  71  17   6
7   1   1  31  22  44
8   1   2  54  18  22
9   1  21  47   4  26
10  1   1  40  23  34
11  1  11  66   9  12
12  1  10  68   8  12

In [102]:
X = df2.values
print(X)

[[ 1  7 26  6 60]
 [ 1  1 29 15 52]
 [ 1 11 56  8 20]
 [ 1 11 31  8 47]
 [ 1  7 52  6 33]
 [ 1 11 55  9 22]
 [ 1  3 71 17  6]
 [ 1  1 31 22 44]
 [ 1  2 54 18 22]
 [ 1 21 47  4 26]
 [ 1  1 40 23 34]
 [ 1 11 66  9 12]
 [ 1 10 68  8 12]]


In [103]:
# Find the transpose of the x matrix
Xt = X.T

# Display the transposed matrix
print("Transpuesta de x:")
print(Xt)

Transpuesta de x:
[[ 1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 7  1 11 11  7 11  3  1  2 21  1 11 10]
 [26 29 56 31 52 55 71 31 54 47 40 66 68]
 [ 6 15  8  8  6  9 17 22 18  4 23  9  8]
 [60 52 20 47 33 22  6 44 22 26 34 12 12]]


In [104]:
# Calculate the matrix product of x_transpose and x
xt_x = Xt @ X

# Calculate the determinant of xt_x
determinant = np.linalg.det(xt_x)

# Display the determinant
print("Determinante de (x_transpose * x):")
display(determinant)
print(xt_x)

Determinante de (x_transpose * x):


np.float64(27717211679.99304)

[[   13    97   626   153   390]
 [   97  1139  4922   769  2620]
 [  626  4922 33050  7201 15739]
 [  153   769  7201  2293  4628]
 [  390  2620 15739  4628 15062]]


In [105]:
# Calculate the inverse of xt_x
xt_x_inv = np.linalg.inv(xt_x)

# Display the inverse matrix
print("Inversa de (x_transpose * x):")
print(xt_x_inv)

Inversa de (x_transpose * x):
[[ 8.20654575e+02 -8.44180186e+00 -8.45777985e+00 -8.63453878e+00
  -8.28974378e+00]
 [-8.44180186e+00  9.27104019e-02  8.56862094e-02  9.26373566e-02
   8.44549553e-02]
 [-8.45777985e+00  8.56862094e-02  8.75602572e-02  8.78666397e-02
   8.55980995e-02]
 [-8.63453878e+00  9.26373566e-02  8.78666397e-02  9.52014097e-02
   8.63919188e-02]
 [-8.28974378e+00  8.44549553e-02  8.55980995e-02  8.63919188e-02
   8.40311912e-02]]


In [106]:
y= df['Y'].values
betas = xt_x_inv @ Xt @ y
betas

array([62.4053693 ,  1.55110265,  0.51016758,  0.1019094 , -0.14406103])

In [107]:
########## CALCULO DEL ERROR #######################
df['Y_pred'] = betas[0] + betas[1]*df['X1'] + betas[2]*df['X2'] + betas[3]*df['X3'] + betas[4]*df['X4']
df

Y  X1  X2  X3  X4      Y_pred
0    78.5   7  26   6  60   78.495240
1    74.3   1  29  15  52   72.788799
2   104.3  11  56   8  20  105.970938
3    87.6  11  31   8  47   89.327100
4    95.9   7  52   6  33   95.649244
5   109.2  11  55   9  22  105.274557
6   102.7   3  71  17   6  104.148669
7    72.5   1  31  22  44   75.674989
8    93.1   2  54  18  22   91.721651
9   115.9  21  47   4  26  115.618452
10   83.8   1  40  23  34   81.809016
11  113.3  11  66   9  12  112.327011
12  109.4  10  68   8  12  111.694334

In [108]:
df['Error'] = df['Y'] - df['Y_pred']
df

Y  X1  X2  X3  X4      Y_pred     Error
0    78.5   7  26   6  60   78.495240  0.004760
1    74.3   1  29  15  52   72.788799  1.511201
2   104.3  11  56   8  20  105.970938 -1.670938
3    87.6  11  31   8  47   89.327100 -1.727100
4    95.9   7  52   6  33   95.649244  0.250756
5   109.2  11  55   9  22  105.274557  3.925443
6   102.7   3  71  17   6  104.148669 -1.448669
7    72.5   1  31  22  44   75.674989 -3.174989
8    93.1   2  54  18  22   91.721651  1.378349
9   115.9  21  47   4  26  115.618452  0.281548
10   83.8   1  40  23  34   81.809016  1.990984
11  113.3  11  66   9  12  112.327011  0.972989
12  109.4  10  68   8  12  111.694334 -2.294334

In [109]:
df['Error^2'] = df['Error']**2
df

Y  X1  X2  X3  X4      Y_pred     Error    Error^2
0    78.5   7  26   6  60   78.495240  0.004760   0.000023
1    74.3   1  29  15  52   72.788799  1.511201   2.283728
2   104.3  11  56   8  20  105.970938 -1.670938   2.792032
3    87.6  11  31   8  47   89.327100 -1.727100   2.982875
4    95.9   7  52   6  33   95.649244  0.250756   0.062878
5   109.2  11  55   9  22  105.274557  3.925443  15.409100
6   102.7   3  71  17   6  104.148669 -1.448669   2.098642
7    72.5   1  31  22  44   75.674989 -3.174989  10.080552
8    93.1   2  54  18  22   91.721651  1.378349   1.899847
9   115.9  21  47   4  26  115.618452  0.281548   0.079269
10   83.8   1  40  23  34   81.809016  1.990984   3.964016
11  113.3  11  66   9  12  112.327011  0.972989   0.946708
12  109.4  10  68   8  12  111.694334 -2.294334   5.263969

In [112]:
ErrorTotal = df['Error^2'].sum()
print(ErrorTotal)

47.86363935049883
